version: 2
accept_configuration:
  condition: or
  conditions:
    # Include all windows targets
    - condition: property
      property: target.os
      equals_value: "Windows"
    # Include documentation build
    - condition: property
      property: features
      contains_value: Documentation

instructions:
  Build:
    - type: EnvironmentVariable
      variableName: BUILD_DOCUMENTATION
      variableValue: "1"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
