version: 2
accept_configuration:
  condition: property
  property: target.os
  equals_value: "Windows"

instructions:
  Build:
    - type: EnvironmentVariable
      variableName: BUILD_DOCUMENTATION
      variableValue: "1"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
